# Dependencies
markdown:	kramdown
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		DavidMesa
tagline:	'blog'
description:	'My personal blog.'
url:		http://www.davidmesa.co
commentsystem:	google

comments:
  disqus:
    short_name: davidmesa
    api_key:    xG1KYrl1ln55G0bdAMMUuiiOMQZ1YESzwPkjnzAbYNsET6S1zNQo7TTidJg4F9ft

author:
  name:		'David Mesa'
  url:		https://google.com/+DavidMesaB

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/davidmesa
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/davidmesa
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://google.com/+DavidMesaB
    desc:	Add me on google+

  - icon:	feed
    url:	http://davidmesa.co/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	David Mesa
  url:		http://www.davidmesa.co
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5
